import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { Providers } from "./store/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<div>Loading...</div>}>
      <html lang="en">
        <body className={`antialiased`}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </Suspense>
  );
}
